name: Feature Request
description: Suggest a new feature or enhancement for Katt
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like Katt to...
    validations:
      required: true
  
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, show how you envision using this feature
      placeholder: |
        ```typescript
        describe("New feature", () => {
          it("should support XYZ", async () => {
            // Example code showing the feature
          });
        });
        ```
      render: typescript
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've considered...
  
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of Katt does this feature relate to?
      options:
        - Core API (describe, it, expect)
        - AI Prompting (prompt, promptFile)
        - Matchers (toContain, promptCheck, toBeClassifiedAs)
        - CLI & Execution
        - Configuration
        - Documentation
        - Other
    validations:
      required: true
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information...
